sudo: false
language: node_js
node_js:
  - "10"

cache: yarn

env:
  - HUSKY_SKIP_INSTALL=true

os:
  - linux

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 15;
    fi

install:
  - yarn global add codecov
  - yarn
script:
  - yarn test:older --no-coverage
  - yarn test
after_success:
  - ./cc-test-reporter upload-coverage -i coverage/coverage-final.json
  - codecov
